### ISSUE TITLE
Cant install with Houdini installation through Steam

### ISSUE THREAD

**Issue by mstarktv** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#229]
I installed the latest version of python (3.8.1).

I tried using the "install.bat" like the previous person. I had all of the same issues. However, my install location of Houdini is as follows:

C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie

That is for version 18. I am not super technical with this, so I'm kind of stuck. I tried doing the manual copy to the install location but when I launched Houdini, there was nothing indicating ProRender was installed. 

Any help would be much appreciated! Thank you :)
![Capture](https://user-images.githubusercontent.com/21364274/73627025-00d04f80-4619-11ea-9fda-c98f0b228b82.PNG)

**Comment by hshakula** [comment]
Hi, first of all, it would be nice if you show output in the opened terminal when you run `install.bat`.
For custom installation paths you have two options, both mentioned in INSTALL.md:
> Copy content of hdRpr*.tar.gz to houdini installation directory

or you can run install.py with -i flag so that script will do it for you.

For the second option you need to:
1. Open command prompt
2. run `cd "packagePath"`, where `packagePath` is a path to unzipped hdRpr installation package you download from github
3. run `python -i "C:\Program Files (x86)\Steam\steamapps\common\Houdini Indie"`

**Comment by mstarktv** [comment]
Please excuse my ignorance. None of this makes sense to me. But I did what you said and RPR shows up in LOPs. However, what I'm confused about (And other artists I've spoken to). Does ProRender use it's own shaders, or does it just translate the standard Houdini shaders under the hood? I know on the ProRender site it mentions the Uber Shader...But I know that Houdini's implementation is not the same as the others.

-I may have installed it wrong and things aren't showing up, hence me asking about a Radeon shader.
-I installed it properly, but I'm not 100% sure that I'm using it correctly.

These are the two situations I'm stuck at. Thank you for your help!

**Comment by bsavery** [comment]
Hi @mstarktv please reopen if this is still an issue.
