### ISSUE TITLE
UV Triplanar and Procedural

### ISSUE THREAD

**Issue by AlxndrTheWretch** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#485]
Hi,

I may be missing something, but it seems that ProRender does not recognize the standard "Texture" node in a material library but the USD UV Texture that it does work with doesn't seem to have any UV inputs for the RPR Triplanar and UV Procedural nodes to be used in. What is the workflow that these nodes were made for?

**Comment by hshakula** [comment]
Hi, @AlxndrTheWretch,

> it seems that ProRender does not recognize the standard "Texture"

This standard node is not supported because it's implemented through VOP code that is not supported by our renderer.

![image](https://user-images.githubusercontent.com/22181845/125057789-487ec480-e0b2-11eb-98a8-a514164ed80e.png)

> the USD UV Texture that it does work with doesn't seem to have any UV inputs for the RPR Triplanar and UV Procedural nodes to be used in

Am I correctly understood that this

![image](https://user-images.githubusercontent.com/22181845/125056971-6d266c80-e0b1-11eb-9fd8-72144f2034eb.png)

does not work for you?

Quick test project:  [triplanarTest.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6790349/triplanarTest.zip)

**Comment by AlxndrTheWretch** [comment]
That does work! I was certain I had tried that but I guess not. Thanks!
