### ISSUE TITLE
RPR checkboxes in dome light seems like don't work

### ISSUE THREAD

**Issue by dwizor** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#486]
Hello, durning setting passes, i encountered a problem, I wanted to render an emission pass, but it have hdri background baked in it and i wanted it to be transparent. So in RPR tab in dome light i unchecked transparent visibility but it seems like did nothing. Out of curiosity, i marked all checkboxes and it looks like it does not work, my HDR is still visible in the reflections, diffuse, and still appears in emission pass.  
![RPR_houdini_dome_light](https://user-images.githubusercontent.com/68112419/125036380-393c4e80-e093-11eb-8055-b895122e18ef.png)

**Comment by hshakula** [comment]
These checkboxes are working only for the "Light" node (not working for "Dome Light" and "Distant Light"). They do exist on the "Dome Light" and "Distant Light" UI due to the current implementation of light nodes customization in Houdini - whenever you add a custom parameter to the "Light" node it is added also to dome/distant light nodes. So you can freely ignore them as if they are not there at all.

With RPR, you can override reflection, refraction, etc - https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/blender/common_parameters.html#overrides. This is currently not implemented in the Houdini plugin but it's doable. Please let me know if this would fulfill your needs.

**Comment by dwizor** [comment]
Hello, thanks for answer! When it comes to my problem, with the emission pass i found workaround. I will simply throw away this background using alpha channel from beauty, but overrides option looks very nice and could be useful in some cases. 
I generally have a few more questions regarding to RPR in Houdini, can I ask you here?

**Comment by hshakula** [comment]
>  I will simply throw away this background using alpha channel from beauty

But this will not remove it from reflection. I thought that is what you want to achieve, isn't it?

> I generally have a few more questions regarding to RPR in Houdini, can I ask you here?

Sure

**Comment by dwizor** [comment]
> But this will not remove it from reflection. I thought that is what you want to achieve, isn't it?
In this specific case i don't need it. But when trying to remove the background from the emission pass, I also found a problem that it does not work, so I asked about it also because it is a useful option. 

a) How to propely render from RPR in Houdini to image format like .exr? On youtube tutorials about RPR, tutorial ends on export to .rpr file which i dont know exactly know how to use. I found solution to use USD Render ROP, but is it like, it issuppose to be?

b) Is there faster way to add Ordered Render Vars than one by one?(using * dont work) Its very tidious if you want many passes.
![render_product](https://user-images.githubusercontent.com/68112419/125075432-e37d9b80-e0be-11eb-9dc0-fa769a7825c8.png)

c) How to transfer attributes like color, or even any custom to material? If i have any @Cd set in SOP its doesnt matter in RPR, even if principle shader have "Use Point Color" check. 

d) How to use DOF in RPR? I dont see any options to manage this. 

e) Durning moving camera in viewport, with RPR turn on, my scene is disappering for moment when i am moving it(objects turns into tiny dots). On youtube tutorials I did not observe this behavior. Is there option to change this or i have something wrong with renderer? 
![dots](https://user-images.githubusercontent.com/68112419/125076259-fcd31780-e0bf-11eb-928a-7f67501a4690.png)

**Comment by hshakula** [comment]
> a) How to propely render from RPR in Houdini to image format like .exr? On youtube tutorials about RPR, tutorial ends on export to .rpr file which i dont know exactly know how to use. I found solution to use USD Render ROP, but is it like, it is suppose to be?

Yes, `USD Render ROP` is the way to render directly from Houdini. Also, you can export the usd stage and then use `husk` if you wish to go the command-line way. Sample project: [aovTest.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6791280/aovTest.zip). Sample render: [render.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6791289/render.zip)

> b) Is there faster way to add Ordered Render Vars than one by one?(using * dont work) Its very tidious if you want many passes.

`/Render/Products/Vars/*` should work, try it.

> c) How to transfer attributes like color, or even any custom to material? If i have any @cd set in SOP its doesnt matter in RPR, even if principle shader have "Use Point Color" check.

Principled shader support in the RPR plugin is quite limited. Mainly due to the fact that this shader is VOP based. And RPR does not support VOP code. So in our plugin, we try our best approximating it with the existing shaders. Also, currently, there is no way to use an arbitrary attribute of the mesh as a data source for the material (technically, in USD terms, it is called primvar and you would use the primvar reader node to bind those values to the material). Though, I was doing my best to push the RPR devs to add such a possibility. But this feature is still WIP. So the best you can do right now is baking those attributes into textures.

> d) How to use DOF in RPR? I dont see any options to manage this.

Through camera parameters: [aovTest_DOF.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6791371/aovTest_DOF.zip)

> e) Durning moving camera in viewport, with RPR turn on, my scene is disappering for moment when i am moving it(objects turns into tiny dots). On youtube tutorials I did not observe this behavior. Is there option to change this or i have something wrong with renderer?

It's a bug in the renderer. The fix is going to be in the next release. See the second point [here](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/issues/453#issuecomment-813689350).

Also, you can find useful info [here](https://radeon-pro.github.io/RadeonProRenderDocs/en/plugins/houdini/about.html).

**Comment by dwizor** [comment]
Thanks a lot for a detailed explanation and test scenes! 

> So the best you can do right now is baking those attributes into textures.

Hm but how do this with point simulation? I Have grain sim with a lot of points/particles and i don't want to assign any geometry to render it. Is it possible to bake colors from these points?

**Comment by hshakula** [comment]
Points primitive is kinda unique regarding color attribute. I added special handling for the colors.
Check this project: [points.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6792081/points.zip) (note that `Full (Legacy)` quality is used here because the `Full` quality does not support one feature required for colors handling, though it should be in the next release if I'm not mistaken)

**Comment by dwizor** [comment]
Oh, damn. Its works ^^ Thanks for patience!
But i have last question here, if its dont using even shader how to control their PBR values? I am not even sure if its possible in Mantra/Karma( im pretty new to Houdini, im using this software a week) But for example what if i would like to have them metalic or maybe o bit more rough or reflective?

**Comment by hshakula** [comment]
Technically, nothing limits us to set any material here. The current implementation simply uses UBER material with only the color input set.

In general, to define a material that would read data from the geometry you need primvar reader node. As I was saying in one of the previous messages, this is not supported yet.

So I don't see a simple clean way to allow you to change the material. If you really need this here and now, I would say that you can take the source code and add the parameters you need, or I can do it for you. Otherwise, you would have to wait until RPR supports primvar reader node.

And you know, while I was writing this, one solution came to my mind. But it would take me at least a half-day to implement. I don't know when I would have time for this.

**Comment by dwizor** [comment]
That's very kind of you, i appreciate your support. If that's something you can do, it would help me a lot. I don't have a deadline for tomorrow for it but within a week I'd have to have it done. So take your time, if not , no problem, I will maybe try to render it in a mantra / karma

**Comment by hshakula** [comment]
I finally got time to check this. Actually, it's not possible to implement a generic primvar reader node with the current RPR API. The current API does not give us any way to get such values as face index or barycentric coordinates that are required to implement `faceVarying` and `vertex` interpolated primvars.

For your particular case - HdPoints with custom material - we technically need only support for the `uniform` interpolation that corresponds to the instance index in the case of HdPoints. That's how currently displayColor primvar support is implemented for HdPoints. But without the primvar reader node support, all of this makes almost no sense.

So the best I can do to help you with your need to edit the material applied to HdPoints is to allow you to control the material parameters through HdPoints primitive (e.g. by using the `Edit Properties` node). Let me know if you still need it or if you decided to use Karma/Mantra for this instead.

**Comment by dwizor** [comment]
I used Mantra to render in my case. But anyway, thanks for willingness to help and I hope that in the future I will use this engine.
