### ISSUE TITLE
Custom Noise Displacement Texture

### ISSUE THREAD

**Issue by petermandk** [GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD#490]
<img width="691" alt="Screenshot 2021-07-18 174909" src="https://user-images.githubusercontent.com/87500136/126073929-c8a0216e-11a5-4617-8af5-be7a83230974.png">

<img width="949" alt="Screenshot 2021-07-18 175737" src="https://user-images.githubusercontent.com/87500136/126073967-dd5b5a71-daa1-4062-9597-be7a880bf703.png">

I was wondering, is it possible, to create custom input texture similar to this i created in Karma? USDTexture image files creates just fine displacement, but but once i input custom noise VOP node seems like render does not read it.  RPR noise texture does not work also, am I missing something? 

Here is my file:
https://drive.google.com/file/d/1Yh9AafCY4CsNrMB3n-vk625ZFyAtxnG6/view?usp=sharing

**Comment by hshakula** [comment]
You cannot use any VOP code-based nodes with RPR. It's not supported.

Generally, you can only use RPR-specific nodes, USD-specific nodes, and some variations of the principled shader (when this node is not translated to VOP code).

> RPR noise texture does not work also, am I missing something?

Just tried, looks like it works:
![image](https://user-images.githubusercontent.com/22181845/126074546-22e53ddc-0302-4c75-b723-a57ed1fb52e1.png)

btw, I noticed you were trying to subdivide the plane but you did not mark it as subdivision surface, is it intentional? You can do it here:
![image](https://user-images.githubusercontent.com/22181845/126074529-2729bd56-9033-4f63-9eea-55c8df200440.png)

This would activate the `subdivision level` setting:
![image](https://user-images.githubusercontent.com/22181845/126074588-02998168-9971-4e6b-8e4a-2ee973f4d12b.png)

**Comment by petermandk** [comment]
Thank you for fast answer, would you mind to share your file? Dont know how to recreate this, maybe primvarreader settings is what i am doing wrong.

**Comment by hshakula** [comment]
[RPR_mat_test.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderUSD/files/6836953/RPR_mat_test.zip)

**Comment by petermandk** [comment]
Thank you for file, i see how you get UV / st  variable/"attribute". Is it possible to get also prim/point color from geomety this way somehow? I was assuming that displayColor would get it but with no luck.
